

export const languages=["English", "Spanish", "French", "German", "Italian", "Russian", "Arabic", "Chinese", "Japanese", "Portuguese", "Dutch", "Swahili", "Hindi", "Turkish", "Korean", "Greek", "Danish", "Swedish", "Norwegian", "Finnish"];

export const eyeColors = ["Black", "Brown", "Grey", "Blue", "Green", "Hazel", "Amber", "Golden", "Red", "Violet", "Albinism", "Multicolored", "Pink", "Yellow", "Silver"];

export const hairColors = ["Black", "Blonde", "Brown", "Red", "White", "Grey", "Auburn", "Chestnut", "Burgundy", "Ash", "Platinum Blonde", "Dirty Blonde", "Caramel", "Copper", "Strawberry Blonde"];
export const hairTypes = ["Curly", "Wavy", "Straight"];
export const hairTextures = ["Fine", "Medium", "Coarse"];
export const hairFullness = ["Thin", "Medium", "Thick"];

export const skinColors = ["Light", "Fair", "Medium", "Olive", "Brown", "Black", "Albino", "Tan", "Ruddy", "Freckled", "Rosy", "Porcelain"];

export const bodyBuilds=["Slim/Slender","Athletic","Curvy"];

export const bloodTypes = [
    "A+",
    "A-",
    "B+",
    "B-",
    "AB+",
    "AB-",
    "O+",
    "O-"
];

export const dominantHands = ["Right Handed","Left Handed","Ambidextrous"]

export const eyeVisions = ["Good", "Normal", "Fair(need corrective lenses)", "Poor(need corrective lenses)"];

export const eyeVisionsLenses = ["Nearsighted", "Farsighted", "Astigmatism"];

export const physicalTraits=["Baldness","Premature graying","Dimples","Freckles","Double Eyelid","Hearing impairments","Periodontal/Orthodontic work","Cleft chin","Roman nose"];

export const maritalStatuses = ["Single", "Married", "Divorced", "Widowed", "Separated", "Engaged", "Common-Law", "Domestic Partnership"];

export const sexualOrientations = ["Heterosexual", "Homosexual", "Bisexual", "Asexual", "Pansexual", "Omnisexual", "Demisexual", "Queer", "Questioning"];

export const activity = ["Athletic", "Active", "Average", "Inactive"];

export const personalities = ["Extrovert", "Slightly Extrovert", "Average", "Slightly Introvert", "Introvert"];

export const educationLevels = ["No Formal Education", "Elementary School", "Middle School", "High School", "Trade/Technical/Vocational Training", "Associate Degree", "Bachelor's Degree", "Master's Degree", "Doctorate Degree", "Postdoctoral", "Medical Degree", "Law Degree"];

export const skillTypes=["Technically", "Mechanically"];

export const skills=["Math", "Reading", "Writing", "Research", "Science", "Athletics", "Artistically","Musically"];

export const usStatuses = ["US Citizen", "Permanent Resident", "Temporary Resident", "Undocumented Immigrant", "DACA Recipient", "Visa Holder", "Asylum Seeker", "Refugee", "Naturalized Citizen", "Dual Citizen", "Expatriate"];

export const relationships = ["Family", "Friend", "Colleague", "Romantic Partner", "Acquaintance", "Mentor", "Mentee", "Neighbor", "Classmate", "Teammate"];

export const race = ["Asian", "White/Caucasian", "Black/African American", "Native American/Alaska Native", "Native Hawaiian/Other Pacific Islander", "Hispanic"];

export const languageFluency = ["Native", "Fluent", "Proficient", "Intermediate", "Elementary", "Pre-Intermediate", "Upper-Intermediate", "Advanced", "Limited", "No Proficiency"];

export const fBaldness="Significant baldness under age 40(Female)/50(Male)";
export const familySide=["Maternal","Paternal"];

export const familyTrait=[fBaldness,];



export const drugs = [
    "Cocaine",
    "LSD",
    "Barbiturates",
    "Narcotics",
    "Opiates",
    "Amphetamines",
    "Hallucinogens",
    "Tranquilizers",
    "PCP",
    "Steroids"
]


export const medicalHistory = [

];

export const physicalHistory = [
    'received blood transfusion','exposed to radiation or toxic chemicals'
];

export const legalHistory = [
    
];

export const legalHistory_p12m = [
    'in jail'
];

export const symptomHistory = [

];

export const symptomHistory_p12m = [
    'gonorrhea or chlamydia','syphilis'
];

export const symptomHistory_p12m_contact = [
    'active viral hepatitis',
    
    
    
    ///tbd
    'had sex with a man who has had sex with another man in the past 5 years'
];





export const ethnicities = [
    "African",
    "African American",
    "Alaska Native",
    "Arab",
    "Asian",
    "Biracial",
    "Caucasian",
    "Hispanic",
    "Indigenous",
    "Latino",
    "Middle Eastern",
    "Native American",
    "Pacific Islander",
    "South Asian",
    "White",
    "Other"
];

export const nationalities = [
    "Afghan",
    "Albanian",
    "Algerian",
    "American",
    "Andorran",
    "Angolan",
    "Antiguans",
    "Argentinean",
    "Armenian",
    "Australian",
    "Austrian",
    "Azerbaijani",
    "Bahamian",
    "Bahraini",
    "Bangladeshi",
    "Barbadian",
    "Barbudans",
    "Batswana",
    "Belarusian",
    "Belgian",
    "Belizean",
    "Beninese",
    "Bhutanese",
    "Bolivian",
    "Bosnian",
    "Brazilian",
    "British",
    "Bruneian",
    "Bulgarian",
    "Burkinabe",
    "Burmese",
    "Burundian",
    "Cambodian",
    "Cameroonian",
    "Canadian",
    "Cape Verdean",
    "Central African",
    "Chadian",
    "Chilean",
    "Chinese",
    "Colombian",
    "Comoran",
    "Congolese",
    "Costa Rican",
    "Croatian",
    "Cuban",
    "Cypriot",
    "Czech",
    "Danish",
    "Djibouti",
    "Dominican",
    "Dutch",
    "East Timorese",
    "Ecuadorean",
    "Egyptian",
    "Emirian",
    "Equatorial Guinean",
    "Eritrean",
    "Estonian",
    "Ethiopian",
    "Fijian",
    "Filipino",
    "Finnish",
    "French",
    "Gabonese",
    "Gambian",
    "Georgian",
    "German",
    "Ghanaian",
    "Greek",
    "Grenadian",
    "Guatemalan",
    "Guinea-Bissauan",
    "Guinean",
    "Guyanese",
    "Haitian",
    "Herzegovinian",
    "Honduran",
    "Hungarian",
    "I-Kiribati",
    "Icelander",
    "Indian",
    "Indonesian",
    "Iranian",
    "Iraqi",
    "Irish",
    "Israeli",
    "Italian",
    "Ivorian",
    "Jamaican",
    "Japanese",
    "Jordanian",
    "Kazakhstani",
    "Kenyan",
    "Kittian and Nevisian",
    "Kuwaiti",
    "Kyrgyz",
    "Laotian",
    "Latvian",
    "Lebanese",
    "Liberian",
    "Libyan",
    "Liechtensteiner",
    "Lithuanian",
    "Luxembourger",
    "Macedonian",
    "Malagasy",
    "Malawian",
    "Malaysian",
    "Maldivan",
    "Malian",
    "Maltese",
    "Marshallese",
    "Mauritanian",
    "Mauritian",
    "Mexican",
    "Micronesian",
    "Moldovan",
    "Monacan",
    "Mongolian",
    "Moroccan",
    "Mosotho",
    "Motswana",
    "Mozambican",
    "Namibian",
    "Nauruan",
    "Nepalese",
    "New Zealander",
    "Nicaraguan",
    "Nigerian",
    "Nigerien",
    "North Korean",
    "Northern Irish",
    "Norwegian",
    "Omani",
    "Pakistani",
    "Palauan",
    "Panamanian",
    "Papua New Guinean",
    "Paraguayan",
    "Peruvian",
    "Polish",
    "Portuguese",
    "Qatari",
    "Romanian",
    "Russian",
    "Rwandan",
    "Saint Lucian",
    "Salvadoran",
    "Samoan",
    "San Marinese",
    "Sao Tomean",
    "Saudi",
    "Scottish",
    "Senegalese",
    "Serbian",
    "Seychellois",
    "Sierra Leonean",
    "Singaporean",
    "Slovakian",
    "Slovenian",
    "Solomon Islander",
    "Somali",
    "South African",
    "South Korean",
    "Spanish",
    "Sri Lankan",
    "Sudanese",
    "Surinamer",
    "Swazi",
    "Swedish",
    "Swiss",
    "Syrian",
    "Taiwanese",
    "Tajik",
    "Tanzanian",
    "Thai",
    "Togolese",
    "Tongan",
    "Trinidadian or Tobagonian",
    "Tunisian",
    "Turkish",
    "Tuvaluan",
    "Ugandan",
    "Ukrainian",
    "Uruguayan",
    "Uzbekistani",
    "Venezuelan",
    "Vietnamese",
    "Welsh",
    "Yemenite",
    "Zambian",
    "Zimbabwean"
];

export const countryList = [
	"Afghanistan",
	"Albania",
	"Algeria",
	"American Samoa",
	"Andorra",
	"Angola",
	"Anguilla",
	"Antarctica",
	"Antigua and Barbuda",
	"Argentina",
	"Armenia",
	"Aruba",
	"Australia",
	"Austria",
	"Azerbaijan",
	"Bahamas (the)",
	"Bahrain",
	"Bangladesh",
	"Barbados",
	"Belarus",
	"Belgium",
	"Belize",
	"Benin",
	"Bermuda",
	"Bhutan",
	"Bolivia (Plurinational State of)",
	"Bonaire, Sint Eustatius and Saba",
	"Bosnia and Herzegovina",
	"Botswana",
	"Bouvet Island",
	"Brazil",
	"British Indian Ocean Territory (the)",
	"Brunei Darussalam",
	"Bulgaria",
	"Burkina Faso",
	"Burundi",
	"Cabo Verde",
	"Cambodia",
	"Cameroon",
	"Canada",
	"Cayman Islands (the)",
	"Central African Republic (the)",
	"Chad",
	"Chile",
	"China",
	"Christmas Island",
	"Cocos (Keeling) Islands (the)",
	"Colombia",
	"Comoros (the)",
	"Congo (the Democratic Republic of the)",
	"Congo (the)",
	"Cook Islands (the)",
	"Costa Rica",
	"Croatia",
	"Cuba",
	"Curaçao",
	"Cyprus",
	"Czechia",
	"Côte d'Ivoire",
	"Denmark",
	"Djibouti",
	"Dominica",
	"Dominican Republic (the)",
	"Ecuador",
	"Egypt",
	"El Salvador",
	"Equatorial Guinea",
	"Eritrea",
	"Estonia",
	"Eswatini",
	"Ethiopia",
	"Falkland Islands (the) [Malvinas]",
	"Faroe Islands (the)",
	"Fiji",
	"Finland",
	"France",
	"French Guiana",
	"French Polynesia",
	"French Southern Territories (the)",
	"Gabon",
	"Gambia (the)",
	"Georgia",
	"Germany",
	"Ghana",
	"Gibraltar",
	"Greece",
	"Greenland",
	"Grenada",
	"Guadeloupe",
	"Guam",
	"Guatemala",
	"Guernsey",
	"Guinea",
	"Guinea-Bissau",
	"Guyana",
	"Haiti",
	"Heard Island and McDonald Islands",
	"Holy See (the)",
	"Honduras",
	"Hong Kong",
	"Hungary",
	"Iceland",
	"India",
	"Indonesia",
	"Iran (Islamic Republic of)",
	"Iraq",
	"Ireland",
	"Isle of Man",
	"Israel",
	"Italy",
	"Jamaica",
	"Japan",
	"Jersey",
	"Jordan",
	"Kazakhstan",
	"Kenya",
	"Kiribati",
	"Korea (the Democratic People's Republic of)",
	"Korea (the Republic of)",
	"Kuwait",
	"Kyrgyzstan",
	"Lao People's Democratic Republic (the)",
	"Latvia",
	"Lebanon",
	"Lesotho",
	"Liberia",
	"Libya",
	"Liechtenstein",
	"Lithuania",
	"Luxembourg",
	"Macao",
	"Madagascar",
	"Malawi",
	"Malaysia",
	"Maldives",
	"Mali",
	"Malta",
	"Marshall Islands (the)",
	"Martinique",
	"Mauritania",
	"Mauritius",
	"Mayotte",
	"Mexico",
	"Micronesia (Federated States of)",
	"Moldova (the Republic of)",
	"Monaco",
	"Mongolia",
	"Montenegro",
	"Montserrat",
	"Morocco",
	"Mozambique",
	"Myanmar",
	"Namibia",
	"Nauru",
	"Nepal",
	"Netherlands (the)",
	"New Caledonia",
	"New Zealand",
	"Nicaragua",
	"Niger (the)",
	"Nigeria",
	"Niue",
	"Norfolk Island",
	"Northern Mariana Islands (the)",
	"Norway",
	"Oman",
	"Pakistan",
	"Palau",
	"Palestine, State of",
	"Panama",
	"Papua New Guinea",
	"Paraguay",
	"Peru",
	"Philippines (the)",
	"Pitcairn",
	"Poland",
	"Portugal",
	"Puerto Rico",
	"Qatar",
	"Republic of North Macedonia",
	"Romania",
	"Russian Federation (the)",
	"Rwanda",
	"Réunion",
	"Saint Barthélemy",
	"Saint Helena, Ascension and Tristan da Cunha",
	"Saint Kitts and Nevis",
	"Saint Lucia",
	"Saint Martin (French part)",
	"Saint Pierre and Miquelon",
	"Saint Vincent and the Grenadines",
	"Samoa",
	"San Marino",
	"Sao Tome and Principe",
	"Saudi Arabia",
	"Senegal",
	"Serbia",
	"Seychelles",
	"Sierra Leone",
	"Singapore",
	"Sint Maarten (Dutch part)",
	"Slovakia",
	"Slovenia",
	"Solomon Islands",
	"Somalia",
	"South Africa",
	"South Georgia and the South Sandwich Islands",
	"South Sudan",
	"Spain",
	"Sri Lanka",
	"Sudan (the)",
	"Suriname",
	"Svalbard and Jan Mayen",
	"Sweden",
	"Switzerland",
	"Syrian Arab Republic",
	"Taiwan",
	"Tajikistan",
	"Tanzania, United Republic of",
	"Thailand",
	"Timor-Leste",
	"Togo",
	"Tokelau",
	"Tonga",
	"Trinidad and Tobago",
	"Tunisia",
	"Turkey",
	"Turkmenistan",
	"Turks and Caicos Islands (the)",
	"Tuvalu",
	"Uganda",
	"Ukraine",
	"United Arab Emirates (the)",
	"United Kingdom of Great Britain and Northern Ireland (the)",
	"United States Minor Outlying Islands (the)",
	"United States of America (the)",
	"Uruguay",
	"Uzbekistan",
	"Vanuatu",
	"Venezuela (Bolivarian Republic of)",
	"Viet Nam",
	"Virgin Islands (British)",
	"Virgin Islands (U.S.)",
	"Wallis and Futuna",
	"Western Sahara",
	"Yemen",
	"Zambia",
	"Zimbabwe",
	"Åland Islands"
];